  GNU nano 5.8                                                                                    docker-compose.yaml                                                                                              
version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "8000:8000"

